import {
  ERROR_CATALOG,
  ERROR_CODES,
  type ErrorCode,
  ExitCode,
  type ExitCodeValue,
  TROUBLESHOOTING_TOPICS,
  type TroubleshootingTopic,
  topicAnchor,
  WARNING_CATALOG,
  type WarningCode,
} from './errors.ts';
import { documentJsonSchema } from './json-schema.ts';
import { DOCUMENTS } from './registry.ts';

const EXIT_MEANINGS: Record<number, string> = {
  [ExitCode.OK]: 'Success. Warnings may be present.',
  [ExitCode.INTERNAL]: 'Unexpected internal error. This is a bug.',
  [ExitCode.USAGE]: 'Usage error: unknown command or option, missing project, unknown id or name.',
  [ExitCode.INPUT_INVALID]: 'An input document is invalid. The error lists every issue with a file and a path.',
  [ExitCode.GENERATION_FAILED]: 'Generation failed for a reason other than invalid input.',
  [ExitCode.OUTPUT_INVALID]:
    'Generated output failed a validation check (with --strict, a warning too). The outputs were still written.',
  [ExitCode.PARTIAL_FAILURE]: 'A batch finished but some assets failed.',
  [ExitCode.ENVIRONMENT]: 'The machine is missing something td2d needs. Run `td2d doctor`.',
  [ExitCode.CANCELLED]: 'Cancelled by SIGINT or SIGTERM.',
};

/** GitHub-style heading anchor for an error code. */
export function errorAnchor(code: string): string {
  return code.toLowerCase();
}

/** Where an error or warning code is described, relative to the repository root. */
export function codeDocsPath(code: string): string {
  return `docs/reference/errors.md#${errorAnchor(code)}`;
}

/** The troubleshooting section for a topic, relative to the repository root. */
export function topicDocsPath(topic: TroubleshootingTopic): string {
  return `docs/guide/troubleshooting.md#${topicAnchor(topic)}`;
}

export interface CodeExplanation {
  readonly code: string;
  readonly kind: 'error' | 'warning';
  /** Null for warnings, which never change the exit code. */
  readonly exit: ExitCodeValue | null;
  readonly summary: string;
  readonly detail: string | null;
  readonly hint: string;
  readonly topic: { readonly id: TroubleshootingTopic; readonly title: string; readonly docs: string };
  readonly docs: string;
}

const isErrorCode = (code: string): code is ErrorCode => Object.hasOwn(ERROR_CATALOG, code);
const isWarningCode = (code: string): code is WarningCode => Object.hasOwn(WARNING_CATALOG, code);

/** Everything the catalogue says about a code, or null for an unknown code. Case-insensitive. */
export function explainCode(input: string): CodeExplanation | null {
  const code = input.trim().toUpperCase();
  const topic = (id: TroubleshootingTopic) => ({ id, title: TROUBLESHOOTING_TOPICS[id], docs: topicDocsPath(id) });
  if (isErrorCode(code)) {
    const e = ERROR_CATALOG[code];
    return {
      code,
      kind: 'error',
      exit: e.exit,
      summary: e.summary,
      detail: e.detail,
      hint: e.hint,
      topic: topic(e.topic),
      docs: codeDocsPath(code),
    };
  }
  if (isWarningCode(code)) {
    const w = WARNING_CATALOG[code];
    return {
      code,
      kind: 'warning',
      exit: null,
      summary: w.summary,
      detail: null,
      hint: w.hint,
      topic: topic(w.topic),
      docs: codeDocsPath(code),
    };
  }
  return null;
}

/** Every known code, errors first. */
export const ALL_CODES: readonly string[] = [...ERROR_CODES, ...Object.keys(WARNING_CATALOG)];

const topicLink = (topic: TroubleshootingTopic) =>
  `[${TROUBLESHOOTING_TOPICS[topic]}](../guide/troubleshooting.md#${topicAnchor(topic)})`;

/** The error reference page, generated from the error catalogue. */
export function renderErrorReference(): string {
  const lines: string[] = [
    '# Error and warning reference',
    '',
    '<!-- Generated by `pnpm generate` from packages/schema/src/errors.ts. Do not edit by hand. -->',
    '',
    'Every failing command reports an error with a stable `code`, a `message`, an optional list of `issues`',
    '(each with a `file` and a `path`), a `hint` and a `docs` link to this page.',
    'With `--json` the error is the `error` field of the envelope on stdout.',
    '`td2d explain <code>` prints any entry below, for errors and warnings alike.',
    '',
    '## Exit codes',
    '',
    '| Exit code | Meaning |',
    '|---|---|',
    ...Object.values(ExitCode).map((code) => `| ${code} | ${EXIT_MEANINGS[code]} |`),
    '',
    '## Errors',
    '',
  ];
  for (const code of ERROR_CODES) {
    const entry = ERROR_CATALOG[code];
    lines.push(
      `### ${code}`,
      '',
      `Exit code ${entry.exit}. ${entry.summary}`,
      '',
      entry.detail,
      '',
      `Fix: ${entry.hint}`,
      '',
      `More: ${topicLink(entry.topic)}`,
      '',
    );
  }
  lines.push(
    '## Warnings',
    '',
    'Warnings never change the exit code, except that `--strict` fails on validation warnings.',
    '',
  );
  for (const [code, entry] of Object.entries(WARNING_CATALOG)) {
    lines.push(`### ${code}`, '', entry.summary, '', `Fix: ${entry.hint}`, '', `More: ${topicLink(entry.topic)}`, '');
  }
  return lines.join('\n');
}

const REFERENCE_PAGES: Readonly<Record<string, string>> = {
  manifest: 'manifest.md',
  'batch-report': 'batch-report.md',
  'aseprite-sheet': 'export-formats.md#aseprite-json',
  'aseprite-sheet-array': 'export-formats.md#aseprite-json',
  'pixi-sheet': 'export-formats.md#pixi',
  'phaser-atlas': 'export-formats.md#phaser-atlas',
  'cli-envelope': 'cli.md',
  'progress-event': 'cli.md',
};

/** The schema reference page: every document type with its top-level fields. */
export function renderSchemaReference(): string {
  const lines: string[] = [
    '# Schema reference',
    '',
    '<!-- Generated by `pnpm generate` from packages/schema/src/registry.ts. Do not edit by hand. -->',
    '',
    'Every file td2d reads or writes has a JSON Schema (draft 2020-12). `td2d schema <name>` prints one,',
    '`td2d schema --write <dir>` writes them all, and the same files are committed in `schemas/`.',
    'Inputs reject unknown keys, so a misspelt setting is reported at its path.',
    '',
    '| Document | Kind | Where it lives |',
    '|---|---|---|',
    ...DOCUMENTS.map((d) => `| [\`${d.name}\`](#${d.name}) | ${d.kind} | ${d.location} |`),
    '',
  ];
  for (const doc of DOCUMENTS) {
    const schema = documentJsonSchema(doc) as {
      properties?: Record<string, { description?: string }>;
      required?: string[];
    };
    const reference = REFERENCE_PAGES[doc.name];
    lines.push(
      `## ${doc.name}`,
      '',
      `${doc.description} ${doc.kind === 'input' ? 'Read from' : 'Written to'} \`${doc.location}\`. Schema: [schemas/${doc.name}.schema.json](../../schemas/${doc.name}.schema.json)${reference ? `; see also [${reference.split('#')[0]}](${reference})` : ''}.`,
      '',
    );
    const properties = Object.entries(schema.properties ?? {}).filter(([key]) => key !== '$schema');
    if (properties.length > 0) {
      lines.push('| Field | Required | Meaning |', '|---|---|---|');
      for (const [key, value] of properties)
        lines.push(
          `| \`${key}\` | ${schema.required?.includes(key) ? 'yes' : ''} | ${(value.description ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`,
        );
      lines.push('');
    }
  }
  return lines.join('\n');
}
