// The example gallery page, generated from the example projects so it lists every asset.
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const INTRO: Record<string, string> = {
  starter: 'The project `td2d init` creates: one crate from four directions.',
  props:
    'Eight props, each built a different way: lathe, CSG, components, mirrored groups, wedges, extrusions, an imported GLB and palette colours.',
  cameras: 'One cottage with every camera and lighting preset, plus automatic scale, counted and mirrored directions.',
  pixel:
    'One mushroom processed with each pixel setting: downscale, palettes, dithering, posterising, outlines, render lines and presets.',
  characters:
    'A rigged knight with idle, walk and attack clips in eight directions, its cape moving in the wind on its own bones, on a grid sheet and on a packed sheet in every export format.',
  fighter:
    'A side-on fighting game: a martial artist with stance, walk, punch, kick and special clips written with the SDK, and the energy ball the special launches, at one shared scale.',
};

function assetIds(dir: string, prefix = ''): string[] {
  const ids: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (!e.isDirectory()) continue;
    const id = prefix ? `${prefix}/${e.name}` : e.name;
    const files = readdirSync(join(dir, e.name));
    if (files.includes('asset.json')) ids.push(id);
    else ids.push(...assetIds(join(dir, e.name), id));
  }
  return ids.sort();
}

/** docs/guide/examples.md */
export function renderGallery(repo: string): string {
  const lines = [
    '# Example gallery',
    '',
    '<!-- Generated by `pnpm generate` from examples/. Do not edit by hand. -->',
    '',
    'Every project under `examples/` is a real td2d project with its outputs committed in `expected/`; the test suite regenerates each one and compares every exported file byte for byte. The previews below are written by `pnpm docs:images`, also checked by the test suite.',
    '',
  ];
  const projects = readdirSync(join(repo, 'examples'))
    .filter((name) => existsSync(join(repo, 'examples', name, 'td2d.project.json')))
    .sort((a, b) => Object.keys(INTRO).indexOf(a) - Object.keys(INTRO).indexOf(b));
  for (const name of projects) {
    const intro = INTRO[name];
    if (!intro) throw new Error(`examples/${name} needs an introduction in scripts/lib/gallery.ts`);
    lines.push(
      `## ${name}`,
      '',
      `${intro} [README](../../examples/${name}/README.md)`,
      '',
      '```sh',
      `cd examples/${name}`,
      'td2d generate',
      '```',
      '',
    );
    lines.push('| Asset | Preview |', '|---|---|');
    for (const id of assetIds(join(repo, 'examples', name, 'assets'))) {
      const definition = JSON.parse(readFileSync(join(repo, 'examples', name, 'assets', id, 'asset.json'), 'utf8')) as {
        description?: string;
      };
      const image = `images/examples/${name}/${id.replace(/\//g, '-')}.png`;
      lines.push(`| \`${id}\`<br>${(definition.description ?? '').replace(/\|/g, '\\|')} | ![${id}](${image}) |`);
    }
    lines.push('');
  }
  lines.push(
    '## engines',
    '',
    "Phaser and PixiJS pages that load the knight's exports and play a clip; a browser test runs them. [README](../../examples/engines/README.md)",
    '',
    '```sh',
    'node examples/engines/serve.ts examples/characters/build/characters/knight/sheets 8080',
    '```',
    '',
    '![The packed knight walking](images/exports/knight-packed-walk.gif)',
    '',
  );
  return lines.join('\n');
}
