// The CLI reference page, generated from the commander program so it cannot drift.
import type { Command, Option } from 'commander';
import { buildProgram } from './program.ts';

export interface CommandHelp {
  /** "generate" or "history list". */
  readonly name: string;
  readonly command: Command;
  /** Lines after "Examples:" that start with "$ ". */
  readonly examples: string[];
  /** Other text after the options, such as notes on output. */
  readonly notes: string[];
}

/** The complete help text of a command, including text added with addHelpText. */
export function fullHelp(cmd: Command): string {
  let out = '';
  cmd.configureOutput({ writeOut: (s) => (out += s), writeErr: (s) => (out += s), outputError: () => {} });
  cmd.outputHelp();
  return out;
}

/** Every leaf command with the examples and notes of its help. */
export function commandHelp(program: Command): CommandHelp[] {
  const out: CommandHelp[] = [];
  const visit = (cmd: Command, prefix: string) => {
    for (const sub of cmd.commands) {
      const name = prefix ? `${prefix} ${sub.name()}` : sub.name();
      if (sub.commands.length > 0) {
        visit(sub, name);
        continue;
      }
      const after = fullHelp(sub).slice(sub.helpInformation().length).split('\n');
      const examples = after.filter((l) => l.trim().startsWith('$ ')).map((l) => l.trim().slice(2));
      const notes = after.map((l) => l.trim()).filter((l) => l && l !== 'Examples:' && !l.startsWith('$ '));
      out.push({ name, command: sub, examples, notes });
    }
  };
  visit(program, '');
  return out;
}

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function optionRows(options: readonly Option[]): string[] {
  return options
    .filter((o) => !o.hidden)
    .map((o) => {
      const extra = [
        o.argChoices ? `One of ${o.argChoices.map((c) => `\`${c}\``).join(', ')}.` : '',
        o.defaultValue !== undefined && o.defaultValue !== false
          ? `Default \`${JSON.stringify(o.defaultValue)}\`.`
          : '',
      ]
        .filter(Boolean)
        .join(' ');
      const description = extra && !/[.!?]$/.test(o.description) ? `${o.description}.` : o.description;
      return `| \`${cell(o.flags)}\` | ${cell(description)}${extra ? ` ${extra}` : ''} |`;
    });
}

const anchor = (name: string) => `td2d-${name.replace(/ /g, '-')}`;

/** docs/reference/cli.md */
export function renderCliReference(program: Command = buildProgram()): string {
  const commands = commandHelp(program);
  const lines = [
    '# CLI reference',
    '',
    '<!-- Generated by `pnpm generate` from the td2d command definitions. Do not edit by hand. -->',
    '',
    'Every command accepts the global options below. With `--json`, stdout carries exactly one JSON envelope',
    '(`{ ok, command, version, durationMs, data, warnings, error? }`) and stderr carries NDJSON logs and progress.',
    'Exit codes and every error code are in the [error reference](errors.md); `td2d explain <code>` prints one entry.',
    '',
    '## Global options',
    '',
    '| Option | Meaning |',
    '|---|---|',
    ...optionRows(program.options),
    '',
    '## Commands',
    '',
    '| Command | Purpose |',
    '|---|---|',
    ...commands.map(
      (c) =>
        `| [\`td2d ${c.name}\`](#${anchor(c.name)}) | ${cell(c.command.description().split(/(?<=\.) /)[0] ?? '')} |`,
    ),
    '',
  ];
  for (const c of commands) {
    const cmd = c.command;
    lines.push(
      `<a id="${anchor(c.name)}"></a>`,
      '',
      `### td2d ${c.name}`,
      '',
      cmd.description(),
      '',
      '```sh',
      `td2d ${c.name} ${cmd.usage()}`.trim(),
      '```',
      '',
    );
    if (cmd.registeredArguments.length > 0) {
      lines.push('| Argument | Meaning |', '|---|---|');
      for (const a of cmd.registeredArguments) {
        const name = `${a.required ? '<' : '['}${a.name()}${a.variadic ? '...' : ''}${a.required ? '>' : ']'}`;
        const def = a.defaultValue !== undefined ? ` Default \`${JSON.stringify(a.defaultValue)}\`.` : '';
        const description = def && !/[.!?]$/.test(a.description) ? `${a.description}.` : a.description;
        lines.push(`| \`${name}\` | ${cell(description)}${def} |`);
      }
      lines.push('');
    }
    const rows = optionRows(cmd.options);
    if (rows.length > 0) lines.push('| Option | Meaning |', '|---|---|', ...rows, '');
    if (c.examples.length > 0) lines.push('Examples:', '', '```sh', ...c.examples, '```', '');
    if (c.notes.length > 0) lines.push(c.notes.join(' '), '');
  }
  return lines.join('\n');
}
