// The barrel, written with the td2d SDK. `td2d asset emit scripts/barrel.ts` writes
// assets/props/barrel/asset.json, which is what td2d actually generates from.
import { defineAsset, lathe, torus } from '@td2d/core/sdk';

const height = 0.9;
const bulge = 0.4;
const end = 0.32;

export default defineAsset({
  id: 'props/barrel',
  type: 'prop',
  description: 'A lathed barrel with two iron hoops, generated by scripts/barrel.ts.',
  directions: 'd4',
  model: {
    parts: [
      lathe({
        id: 'staves',
        material: 'oak',
        segments: 16,
        profile: [
          [0, 0],
          [end, 0],
          [bulge - 0.03, height * 0.2],
          [bulge, height / 2],
          [bulge - 0.03, height * 0.8],
          [end, height],
          [0, height],
        ],
      }),
      torus({
        id: 'hoop',
        material: 'iron',
        radius: bulge - 0.025,
        tube: 0.025,
        radialSegments: 6,
        tubularSegments: 16,
        position: [0, height * 0.22, 0],
        repeat: { count: 2, offset: [0, height * 0.56, 0] },
      }),
    ],
  },
});
